"""AOM — SysML v2 view generator (venture-generic).

Reads <venture>-aom-model-at-C<N>.yaml (the model — single source of truth) and
emits <venture>-aom-at-C<N>.sysml in SysML v2 textual notation.

The YAML is the model; this file and every other rendering are views.
Self-checks run before writing; the file is NOT written on any failure.

View the output in VS Code with the SysIDE extension (free, by Sensmetry),
or any SysML v2 (2024-xx) textual-notation tool.
"""
import yaml
import sys, pathlib
if len(sys.argv) != 2:
    print(f"usage: python3 {pathlib.Path(__file__).name} <venture>-MODEL-model-at-C<N>.yaml"); sys.exit(1)
SRC = pathlib.Path(sys.argv[1]).resolve()
assert "-model-" in SRC.name, "model file must be named [venture]-[model]-model-at-C[N].yaml"

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from validate_model import check_or_die, venture_endpoint_ids, is_venture, provenance, jurisdiction_line
check_or_die(SRC)
PROV = provenance(__file__, SRC)  # schema gate — a malformed model fails before any rendering

OUT = SRC.parent / (SRC.name.replace("-model-", "-").rsplit(".", 1)[0] + ".sysml")

m = yaml.safe_load(SRC.read_text())

# ------------------------------------------------------------ self-checks
errs = []
# Endpoint set shared with the validator — never a local literal (VA-64 class, fixed 1 Sep 2026).
actor_ids = set(m["actors"]) | venture_endpoint_ids(m)
# The emitted part name for the venture: its slug, stable and collision-free.
import re as _re
VPART = _re.sub(r"[^a-z0-9]+", "", m["venture"].strip().lower()) or "venture"
functions = {fid for org in m["organisation"].values() for fid in org["functions"]}
comp_ids = set(m["components"])

for cid, c in m["components"].items():
    if c["allocated_to"] not in functions:
        errs.append(f"{cid}: allocated_to '{c['allocated_to']}' is not an org function")

flow_count = 0
via_seen = set()
for cls in ("product", "information", "money"):
    if cls not in m["flows"] or not m["flows"][cls]:
        errs.append(f"flow class '{cls}' is empty — OMM decomposition incomplete")
        continue
    for f in m["flows"][cls]:
        flow_count += 1
        for end in (f["from"], f["to"]):
            if end not in actor_ids:
                errs.append(f"flow {f['name']}: endpoint '{end}' unknown")
        if f.get("via"):
            if f["via"] not in comp_ids:
                errs.append(f"flow {f['name']}: via '{f['via']}' not a registered component")
            via_seen.add(f["via"])
        elif not f.get("flag") and not f.get("doc"):
            errs.append(f"flow {f['name']}: no carrying component and no flag/doc explaining why")

if errs:
    print("SELF-CHECK FAILURES — file not written:")
    for e in errs:
        print("  ✗", e)
    sys.exit(1)

# ------------------------------------------------------------ emit
def ident(s):
    return s.replace("-", "_").replace(" ", "_")

def defname(s):
    return "".join(ch for ch in s if ch.isalnum())

L = []
w = L.append
w(f"// GENERATED from {SRC.name} — do not edit this file; edit the YAML and regenerate.")
w(f"// {PROV}")
w(f"// {m['venture']} · At-Scale Operational Model · {m['state']} · {m['date']}")
w(f"// Jurisdiction: {jurisdiction_line(m)}")
w(f"// Figures are planning inputs; {m.get('economics_ref', 'the venture economics workbook')} governs.")
w("// View with the SysIDE extension for VS Code (SysML v2 textual notation).")
w("")
w(f"package {m['venture'].replace(' ', '')}AOM {{")
w("")
w(f"    doc /* At-Scale Operational Model for {m['venture']} at {m['state'].removeprefix('at-')}.")
w("         Decomposition follows OMM (Simanis & Manuel, IFC 2018):")
w("         actors and org first, then product / information / money flows,")
w("         each flow carried by a Flow-Register component (G3 tab 6). */")
w("")

# Items
w("    package Items {")
items = sorted({f["item"] for cls in m["flows"].values() for f in cls})
for it in items:
    w(f"        item def {it};")
w("    }")
w("")

# Actors
w("    package Actors {")
for aid, a in m["actors"].items():
    w(f"        part def {defname(a['name'])} {{")
    bits = [f"{a['class'].replace('_', '-')}"]
    if a.get("slot"):
        bits.append(f"modular supplier slot {a['slot']}")
    w(f"            doc /* [{' · '.join(bits)}] {a['doc']}")
    if a.get("flag"):
        w(f"                 {a['flag']} */")
    else:
        w("                 */")
    w("        }")
w("    }")
w("")

# Activity definitions
w("    package Activities {")
for cid, c in m["components"].items():
    w(f"        action def {c['def']} {{")
    doc = f"[{cid}] {c['doc']} · DRI: {c['dri']}"
    if c.get("cost_ref"):
        doc += f" · cost: {c['cost_ref']}"
    if c.get("flag"):
        doc += f" · {c['flag']}"
    w(f"            doc /* {doc} */")
    w("        }")
w("    }")
w("")

# Organisation with performed activities (allocation by nesting)
w("    package Organisation {")
w(f"        part {VPART} {{")
w("            doc /* The venture — owns the calibration model and the rules. */")
for oid, org in m["organisation"].items():
    w(f"            part {ident(oid)} {{")
    w(f"                doc /* {org['name']} [{org['op_id']}] · cost: {org['cost_ref']} */")
    for fid, fn in org["functions"].items():
        w(f"                part {ident(fid)} {{")
        fte = fn.get("fte")
        fte_txt = f"{fte} FTE central" if fte is not None else "FTE not derived"
        w(f"                    doc /* {fn['name']} · {fte_txt} · driver: {fn['driver']} */")
        for cid, c in m["components"].items():
            if c["allocated_to"] == fid:
                w(f"                    perform action {ident(c['name'])} : Activities::{c['def']};")
        w("                }")
    w("            }")
w("        }")
w("")
# Actor part usages
for aid, a in m["actors"].items():
    w(f"        part {ident(aid)} : Actors::{defname(a['name'])};")
w("    }")
w("")

# Flows
w("    package Flows {")
for cls in ("product", "information", "money"):
    w(f"        // ---- {cls} flow (OMM)")
    for f in m["flows"][cls]:
        src = f"Organisation::{VPART}" if is_venture(f["from"], m) else f"Organisation::{ident(f['from'])}"
        dst = f"Organisation::{VPART}" if is_venture(f["to"], m) else f"Organisation::{ident(f['to'])}"
        doc = f"item {f['item']}"
        if f.get("via"):
            doc += f" · carried by {f['via']}"
        if f.get("doc"):
            doc += f" · {f['doc']}"
        if f.get("flag"):
            doc += f" · {f['flag']}"
        w(f"        connection {ident(f['name'])} connect {src} to {dst} {{")
        w(f"            doc /* [{cls}] {doc} */")
        w("        }")
    w("")
w("    }")
w("}")

OUT.write_text("\n".join(L) + "\n")
n_comp = len(m["components"])
print(f"self-checks PASS · wrote {OUT.name}: {len(m['actors'])} actors · "
      f"{len(functions)} org functions · {n_comp} components ({len(via_seen)} carrying flows) · {flow_count} flows")
